# Generated by Django 4.2.11 on 2024-03-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dish', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Описание блюда'),
        ),
    ]
