# Generated by Django 4.2.11 on 2024-03-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0001_initial'),
        ('Dish', '0004_alter_dish_category_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='category',
        ),
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.ManyToManyField(to='Category.dishcategory', verbose_name='Категория'),
        ),
    ]
