# Generated by Django 4.2.11 on 2024-03-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About_us', '0002_alter_aboutus_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='text',
            field=models.TextField(max_length=3040, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(max_length=215, verbose_name='Заголовок'),
        ),
    ]
