# Generated by Django 4.2.11 on 2024-03-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drink', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Доступно'),
        ),
    ]
